name: nostart
description: Smoke-Free Malaysia e-Explorace 2021.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^1.0.1
  chewie: ^0.12.2
  audioplayers: 0.19.1
  carousel_slider: ^4.0.0
  flutter_google_places: ^0.3.0
  responsive_flutter: ^0.0.4
  flutter_cube: ^0.1.1
  responsive_framework: ^0.1.4
  loading_overlay: ^0.2.1
  flutter_animated_dialog: ^2.0.1
  shared_preferences: ^2.0.6
  flutter_svg_provider: ^0.1.9
  font_awesome_flutter: ^9.1.0
  uuid: ^3.0.1
  firebase_core: ^1.6.0
  google_maps: ^5.3.0
  cloud_firestore: ^2.5.1
  button3d: ^0.1.1
  geolocator: ^7.6.0
  http: ^0.13.1
  getwidget: ^2.0.3
  animated_text_kit: ^4.2.1
  percent_indicator: ^3.0.1
  progressive_image: ^2.0.0
  url_launcher: ^6.0.10
  footer:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  fluent_ui: ^3.1.0
  universal_html: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lotties/
    - images/
    - images/footerlogo_Desktop.png
    - images/footerlogo_Mobile.png
    - assets/
    - images/kuiz_images/
    - images/keluarga/
    - images/komik/c1/
    - images/komik/c2/
    - images/komik/c3/
    - images/characters/
    - images/puzzles/sihat/
    - images/puzzles/rosak/
    - images/dice/
    - images/checkpoints/
    - 3d-model/lungs/
    
  fonts:
    - family: Header
      fonts:
         - asset: 'fonts/Lucky Boss.ttf'        
    - family: Roboto-Bold
      fonts:
         - asset: 'fonts/Roboto-Bold.ttf'
    - family: Riffic-Bold
      fonts:
         - asset: 'fonts/RifficFree-Bold.ttf'
    - family: Adelia
      fonts:
         - asset: 'fonts/ADELIA.ttf'    
    - family: FontAwesome
      fonts:
         - asset: 'fonts/fa-regular-400.ttf'
    - family: Spongebob
      fonts:
         - asset: 'fonts/SpongeboyMeBob.ttf'
    - family: Provicali
      fonts:
         - asset: 'fonts/Provicali.ttf'
    - family: BestSchool
      fonts:
         - asset: 'fonts/BestSchool.ttf'
    - family: Gient
      fonts:
         - asset: 'fonts/Gient.ttf'
    - family: BebasNeue
      fonts:
         - asset: 'fonts/BebasNeue.ttf'
    - family: Futura
      fonts:
         - asset: 'fonts/Futura.ttf'
    - family: Badabom
      fonts:
         - asset: 'fonts/BADABB.ttf'
    - family: KGHAPPY
      fonts:        
         - asset: 'fonts/KGHAPPYSolid.ttf'
         - asset: 'fonts/KGHAPPYShadows.ttf'
         - asset: 'fonts/KGHAPPY.ttf'
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
